### PR TITLE
Add Star+

### LINKED ISSUE #85: Star+ icon
It would be great if you could bundle a Star+ icon + button.

https://icon-sets.iconify.design/cbi/star-plus/

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #85

### CODE REVIEW

**Comment by felipecrs** [comment]
I tested it and it works. Here's how it looks like:

image

**Comment by felipecrs** [comment]
Also updated the Disney+ icon:

## Before

image

## After

image

**Comment by Nerwyn** [comment]
The logos look good, but you need to switch the target branch to `dev`. `main` is for released code.

**Comment by felipecrs** [comment]
Ops, sorry lol.

**Comment by felipecrs** [comment]
@Nerwyn there we go.

**Pull request merged**
